Update PublishKernelPoolProviders.yml

diff --git a/.github/workflows/PublishKernelPoolProviders.yml b/.github/workflows/PublishKernelPoolProviders.yml
--- a/.github/workflows/PublishKernelPoolProviders.yml
+++ b/.github/workflows/PublishKernelPoolProviders.yml
@@ -10,7 +10,7 @@ on:
     types: [published]
 
 jobs:
-  build:
+   build-provider-package:
     runs-on: ubuntu-latest
 
     strategy:
@@ -49,10 +49,7 @@ jobs:
         run: dotnet build ${{ matrix.package-path }} --configuration Release -p:UsePackages=true
 
       - name: Pack package
-        run: dotnet pack ${{ matrix.package-path }} --configuration Release -p:UsePackages=true -p:PackageVersion=${{ steps.get-version.outputs.package_version }} /p:PackageReleaseNotes="See https://raw.githubusercontent.com/alonf/SemanticKernelPooling/master/README.md" --output ./nupkgs
-
-      - name: Debug Log Packed Packages
-        run: ls -l ./nupkgs
+        run: dotnet pack -c Release -p:PackageVersion=${{ steps.get-version.outputs.package_version }} /p:PackageReleaseNotes="See https://raw.githubusercontent.com/alonf/SemanticKernelPooling/master/README.md" ${{ matrix.package-path }} -p:UsePackages=true  --output ./nupkgs
 
       - name: Publish packages with retry
         env:
@@ -60,6 +57,6 @@ jobs:
         run: |
           for pkg in ./nupkgs/*.nupkg; do
             for i in {1..3}; do
-              dotnet nuget push "$pkg" --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json && break || echo "Failed to push $pkg, attempt $i, retrying in 30 seconds..." && sleep 30;
+              dotnet nuget push ./nupkgs/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json && break || echo "Failed to push $pkg, attempt $i, retrying in 30 seconds..." && sleep 30;
             done
           done
